{
    "name": "MailChimp Connector",
    "version": "17.0.1.0.1",
    "category": "Marketing",
    "summary": "Integrate & Manage MailChimp Operations from Odoo",
    "depends": [
        "mass_mailing",
        "queue_job",
    ],
    "development_status": "Production/Stable",
    "external_dependencies": {"python": ["mailchimp_marketing"]},
    "maintainers": ["ecino"],
    "data": [
        "data/ir_cron.xml",
        "views/mailchimp_accounts_view.xml",
        "views/mailing_contact_view.xml",
        "views/mailing_list_view.xml",
        "views/mailchimp_template_view.xml",
        "views/mass_mailing_view.xml",
        "security/ir.model.access.csv",
    ],
    "author": "Compassion Switzerland",
    "website": "https://github.com/CompassionCH/paid-addons",
    "license": "AGPL-3",
    "demo": [],
    "auto_install": False,
    "installable": True,
}
